# Generated by Django 5.0.1 on 2024-02-06 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_specialities'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.specialities'),
        ),
    ]
