# Generated by Django 5.0.1 on 2024-02-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usermodel_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
