# Generated by Django 5.0.1 on 2024-02-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usermeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
