# Generated by Django 5.0.1 on 2024-03-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
